### ISSUE TITLE
Unused screenProps={rootStore} ?

### ISSUE THREAD

**Issue by mailursubbu** [vonovak/react-navigation-mst-demo#1]
Please treat this as a doubt :-

All the screens seems to be finding the rootStore using the Inject. I see screens getting rootStore using inject as below 

`export const RepoDetailScreen = inject('rootStore')(observer(_RepoDetailScreen));
`
I dont see any screens extracting the rootStore using this.props.screenProps. Is the code related to passing "screenProps={rootStore}" ( as below) can be removed ?

```
export const createMainTabNavigator = rootStore => {
  const TargetComponent = props => {
    return <HomeStack {...props} screenProps={rootStore} />;
  };
```

**Comment by vonovak** [comment]
hi! Thanks for the question. The screen props are provided here https://github.com/vonovak/react-navigation-mst-demo/blob/e543b28e84f18c26f93a3ce54baf8616bfd1f33e/navigation/MainTabNavigator.js#L43

and they are being used here https://github.com/vonovak/react-navigation-mst-demo/blob/e543b28e84f18c26f93a3ce54baf8616bfd1f33e/screens/UserScreen.js#L8

I wouldn't recommend to do this kind of thing as screenProps will probably be deprecated at some point - I just did it to get the demo working quick.

**Comment by mailursubbu** [comment]
Thanks for the inputs !
